- name: Hello world
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 600

    - name: Gather facts
      setup:

    - name: Gather services facts
      service_facts:

    - name: Get python3 version
      shell: "python3 --version | sed 's/Python //'"
      register: python3_ver
      changed_when: false
      failed_when: python3_ver.stdout != "3.9.1"

    - name: Get ansible version
      shell: "ansible --version | grep ^ansible | sed 's/ansible //'"
      register: ansible_ver
      changed_when: false
      failed_when: ansible_ver.stdout != "2.10.6"

    - name: Get ansible-python version
      shell: "ansible --version | grep 'python version =' | sed -r 's/.*= ([0-9]+\\.[0-9]+\\.[0-9]+).*/\\1/'"
      register: ansible_python_ver
      changed_when: false
      failed_when: ansible_python_ver.stdout != "3.9.1"
  
    - name: Print hello world
      debug:
        msg: "Hello World"

